spring:  data:    rest:      base-path: /api/v1
        datasource:    driver-class-name: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://localhost:5432/book-store
    username: postgres
    
  jpa:    show-sql: true